### ISSUE TITLE
Change syntax in premise and conclusion input area

### ISSUE THREAD

**Issue by tillmo** [nadeemn/fitchjs#13]
**Describe the bug**
Change syntax in premise and conclusion input area

**To Reproduce**
Visit (https://nadeemn.github.io/fitchjs/

**Expected behavior**
The new syntax should be used for the example formulas in the text areas

**Comment by nadeemn** [comment]
Hi,
I have changed the syntax to new ones in the placeholder areas. Please check.

**Comment by tillmo** [comment]
works !
