### ISSUE TITLE
Cannot use conjunction elimination

### ISSUE THREAD

**Issue by tillmo** [nadeemn/fitchjs#14]
**Describe the bug**
Cannot use conjunction elimination

**To Reproduce**
1. Go to https://nadeemn.github.io/fitchjs/
2. Enter Premise P∧Q
3. Enter conclusion P
4. press "Begin"
5. Enter formula: P
6. Selection Rule: Elmination, and ∧
7. Select line 1
8. Press "Append"

Then an error occurs "The formula in line 1 must be a conjunction"
Note that the formula in line 1 **is** a conjunction

**Expected behavior**
Proof goes through.

**Comment by nadeemn** [comment]
Hi,
Can you please check now. I have fixed this issue.

**Comment by tillmo** [comment]
good, works!
