### ISSUE TITLE
change symbol for completed proof

### ISSUE THREAD

**Issue by tillmo** [nadeemn/fitchjs#18]
Currenty, a completed proof is marked with a red cross. This should be changed to a green tick.
![Bildschirmfoto von 2024-11-28 20-19-27](https://github.com/user-attachments/assets/4d31c720-58ef-41e8-8238-6da5d7e16795)

**Comment by nadeemn** [comment]
Hi, that is not a red cross indicating its wrong. Its for deleting that step. I have changed so that it can be understandable now.

**Comment by tillmo** [comment]
aha, I understand.  However, I cannot see any change.

**Comment by nadeemn** [comment]
can you check now .
![image](https://github.com/user-attachments/assets/07d22f87-4fea-426c-ab88-9225c6718aaa)

**Comment by tillmo** [comment]
now I can see it, too
