### ISSUE TITLE
Use new syntax when exporting proofs

### ISSUE THREAD

**Issue by tillmo** [nadeemn/fitchjs#19]
also in the rules, the new syntax should be used.
![Bildschirmfoto von 2024-11-28 21-05-02](https://github.com/user-attachments/assets/5bb915d1-6163-45bb-b28d-4f241102bcb7)

**Comment by nadeemn** [comment]
hi,
this issue has been fixed. PFA

![image](https://github.com/user-attachments/assets/299f6fed-dfd6-47da-b1aa-13d697b9c8dd)

**Comment by tillmo** [comment]
good, works!
