### ISSUE TITLE
After an error, contents of text fields should stay

### ISSUE THREAD

**Issue by tillmo** [nadeemn/fitchjs#25]
**Describe the bug**
After an error, contents of text fields vanishes

**To Reproduce**
1. Input a premise P∧Q and a conclusion Q
2. Input formula P∧, select rule∧E and line 1, press "append"
3. The ill-formed formula P∧ vanishes and needs to be re-typed, which can be tedious for complex formulas.
**Expected behavior**
After an error, contents of text fields should stay

**Comment by nadeemn** [comment]
HI,
I was not able to reproduce this issue. For me it was working well. Can you check again. Please find the recording attached.

https://drive.google.com/file/d/1WGnsBcsAyLJcMSnM9c2K_P9ZoF7AsZ94/view

**Comment by tillmo** [comment]
sorry. Indeed, the formula stays. But the selected rule and the line vanishes. They also should stay.

**Comment by nadeemn** [comment]
Hi, I have fixed this issue. Please check now.
